//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_data_dashboard
    {
        public decimal data_dash_id { get; set; }
        public Nullable<decimal> asset_id { get; set; }
        public string data_type_cd { get; set; }
        public string Web_Label { get; set; }
        public string Asset_Description { get; set; }
        public Nullable<System.DateTime> Data_Collection_DateTime { get; set; }
        public string Asset_ID_Ext { get; set; }
        public string Rain_Meter { get; set; }
        public string Average_Level { get; set; }
        public string Ambient_Temp { get; set; }
        public string GPS_Coord_Latitude { get; set; }
        public string GPS_Coord_Longitude { get; set; }
        public string Reading_Date_Time { get; set; }
        public Nullable<System.DateTime> logical_termination_dt { get; set; }
        public string last_update_user_id { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public byte[] row_version { get; set; }
    }
}
