//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_attribute_data
    {
        public decimal asset_attribute_data_id { get; set; }
        public decimal asset_id { get; set; }
        public decimal json_data_id { get; set; }
        public Nullable<decimal> waterLevel { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public System.DateTime reading_dt { get; set; }
        public byte[] row_version { get; set; }
    }
}
