//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_alert_condition
    {
        public decimal asset_alert_condition_id { get; set; }
        public Nullable<decimal> asset_id { get; set; }
        public Nullable<decimal> party_id { get; set; }
        public string alert_name { get; set; }
        public string alert_level_cd { get; set; }
        public string alert_message { get; set; }
        public Nullable<decimal> rpt_tag_key_id { get; set; }
        public string condition_cd { get; set; }
        public string compare_value { get; set; }
        public Nullable<decimal> compare_data_type { get; set; }
        public string alert_color_cd { get; set; }
        public string alert_icon { get; set; }
        public string alert_condition { get; set; }
        public Nullable<System.DateTime> logical_termination_dt { get; set; }
        public string last_update_user_id { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public byte[] row_version { get; set; }
    }
}
