//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class code_domain
    {
        public string code_domain_cd { get; set; }
        public string long_name { get; set; }
        public string display_name { get; set; }
        public string code_domain_description { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string user_defined_string_1 { get; set; }
        public string user_defined_string_2 { get; set; }
        public Nullable<decimal> user_defined_numeric_1 { get; set; }
        public Nullable<decimal> user_defined_numeric_2 { get; set; }
        public Nullable<System.DateTime> logical_termination_dt { get; set; }
        public string last_update_user_id { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public byte[] row_version { get; set; }
    }
}
