//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_contact
    {
        public decimal party_contact_id { get; set; }
        public decimal party_id { get; set; }
        public string party_contact_type_cd { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_initials { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime password_expiration_dt { get; set; }
        public string account_status_cd { get; set; }
        public bool application_user_ind { get; set; }
        public Nullable<System.DateTime> logical_termination_dt { get; set; }
        public string last_update_user_id { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public byte[] row_version { get; set; }
    }
}
