//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_asset
    {
        public decimal asset_id { get; set; }
        public string asset_name { get; set; }
        public string asset_type_cd { get; set; }
        public string asset_description { get; set; }
        public string external_id { get; set; }
        public string street_address_1 { get; set; }
        public string street_address_2 { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public string state_cd { get; set; }
        public string country { get; set; }
        public string gps_location { get; set; }
        public System.DateTime asset_create_dt { get; set; }
        public string asset_created_by { get; set; }
        public Nullable<System.DateTime> logical_termination_dt { get; set; }
        public string last_update_user_id { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public byte[] row_version { get; set; }
        public bool active_ind { get; set; }
        public string activated_by { get; set; }
        public Nullable<System.DateTime> activated_dt { get; set; }
        public decimal manufacturer_id { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string model_number { get; set; }
        public string user_defined_group { get; set; }
        public string installation_type_cd { get; set; }
        public Nullable<decimal> wet_water_level { get; set; }
        public Nullable<decimal> wet_sensor_depth { get; set; }
        public Nullable<decimal> dry_above_grade_offset { get; set; }
        public Nullable<decimal> dry_below_grade_offset { get; set; }
        public bool disable_alarm_ind { get; set; }
        public string location_type { get; set; }
        public string folder_Id { get; set; }
        public string deviceSN { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public Nullable<double> batteryStrength { get; set; }
        public Nullable<double> signalStrength { get; set; }
        public Nullable<double> batteryTypeID { get; set; }
    }
}
