//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_asset_status
    {
        public decimal asset_status_id { get; set; }
        public Nullable<decimal> asset_id { get; set; }
        public Nullable<decimal> inches_full { get; set; }
        public Nullable<decimal> inches_air { get; set; }
        public Nullable<decimal> amount_full { get; set; }
        public string tank_status { get; set; }
        public string status_color { get; set; }
        public Nullable<decimal> status_color_cd { get; set; }
        public Nullable<decimal> capacity { get; set; }
        public Nullable<decimal> last_fill_amount { get; set; }
        public Nullable<System.DateTime> last_fill_dt { get; set; }
        public Nullable<System.DateTime> logical_termination_dt { get; set; }
        public string last_update_user_id { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public byte[] row_version { get; set; }
    }
}
