//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_app_user_party
    {
        public decimal party_id { get; set; }
        public string party_type_cd { get; set; }
        public string legal_name { get; set; }
        public string short_name { get; set; }
        public string entity_type_cd { get; set; }
        public Nullable<System.DateTime> logical_termination_dt { get; set; }
        public string last_update_user_id { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public Nullable<bool> replicate_party_ind { get; set; }
        public byte[] row_version { get; set; }
        public string username { get; set; }
    }
}
