//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_asset_alert_data_tag
    {
        public decimal rpt_tag_key_id { get; set; }
        public string data_tag { get; set; }
        public string data_key_cd { get; set; }
        public string data_label { get; set; }
        public string data_type_cd { get; set; }
    }
}
