//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_latest_asset_json_data
    {
        public decimal asset_id { get; set; }
        public Nullable<System.DateTime> collection_dt { get; set; }
        public Nullable<decimal> json_data_id { get; set; }
        public Nullable<int> data_count { get; set; }
        public string data_json { get; set; }
    }
}
