//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lu_party_contact_type_cd
    {
        public string code { get; set; }
        public string party_contact_type_cd { get; set; }
        public string party_contact_type_description { get; set; }
        public string data_grouping_1 { get; set; }
        public string data_grouping_2 { get; set; }
        public string data_grouping_3 { get; set; }
        public string display_name { get; set; }
        public string external_data_map_1 { get; set; }
        public string external_data_map_2 { get; set; }
        public string external_data_map_3 { get; set; }
        public string external_data_source_cd_1 { get; set; }
        public string external_data_source_cd_2 { get; set; }
        public string external_data_source_cd_3 { get; set; }
        public bool is_default_ind { get; set; }
        public bool is_numeric_ind { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public string last_update_user_id { get; set; }
        public Nullable<System.DateTime> logical_termination_dt { get; set; }
        public string long_name { get; set; }
        public string parent_code_domain_cd { get; set; }
        public string parent_code_domain_value_cd { get; set; }
        public byte[] row_version { get; set; }
        public Nullable<int> sort_order { get; set; }
        public Nullable<decimal> user_defined_numeric_1 { get; set; }
        public Nullable<decimal> user_defined_numeric_2 { get; set; }
        public Nullable<decimal> user_defined_numeric_3 { get; set; }
        public string user_defined_string_1 { get; set; }
        public string user_defined_string_2 { get; set; }
        public string user_defined_string_3 { get; set; }
    }
}
