//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_manufacturer
    {
        public decimal manufacturer_id { get; set; }
        public string manufacturer_name { get; set; }
        public string token_url { get; set; }
        public string data_url { get; set; }
        public string access_user_nm { get; set; }
        public string access_pw { get; set; }
        public string access_grant_type { get; set; }
        public string access_client_id { get; set; }
        public string access_client_secret { get; set; }
        public Nullable<System.DateTime> logical_termination_dt { get; set; }
        public string last_update_user_id { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public byte[] row_version { get; set; }
    }
}
